### ISSUE TITLE
Upgrade to Docker 1.10

### ISSUE THREAD

**Issue by roll** [respect31/docker-cloud-example#1]
With `docker 1.10` stack file version 2 will be available. 

Hopefully it could be written with additional keys like:

```
stack:
  namespace: example
  environments:
    - production
    - staging
services:
  ...
```

So it could be used instead of magic line:

```
# {"namespace": "example", "environments": ["staging", "production"]}
```
